apiVersion: apps/v1
kind: Deployment
## Deployment 세부 정보
metadata:
  name: spring-deployment


spec:
  replicas: 5
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
        - name: spring-container
          image: spring-server:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080



